replicaCount: 1

resources:
  requests:
    memory: 1Gi
    cpu: 500m

openmetadata:
  config:
    database:
      host: postgres.dev
      port: 5432
      databaseName: openmetadata
      auth:
        username: openmetadata
        existingSecret: openmetadata-db
    elasticsearch:
      host: elasticsearch.dev
      port: 9200
    pipelineServiceClientConfig:
      metadataApiEndpoint: http://openmetadata.dev:8585/api

ingress:
  enabled: true
  hosts:
    - openmetadata.dev.local
