replicaCount: 2

resources:
  requests:
    memory: 2Gi
    cpu: 1000m

supersetNode:
  connections:
    db_host: postgres.prod
    db_port: 5432
    db_name: superset
    db_user: superset

extraEnv:
  SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY}"

ingress:
  enabled: true
  hosts:
    - superset.prod.local

caching:
  enabled: true
  cacheType: redis
  redisHost: redis.prod
